### ISSUE TITLE
Disable renderer for one class

### ISSUE THREAD

**Issue by chrisriesgo** [nativecode-dev/oss-xamarin#23]
How do you disable your renderers on a one-off basis? I have one PageRenderer where I'm inflating a custom view and need to do some of my own things that I think are being interrupted by your renderers. Can I skip them in this one class? (I seem to remember seeing a commit message or something about that being possible)

**Comment by mikepham** [comment]
There are a few functions you can call to not enable all the renderers, but it's at the app-level and not a page-level. Please see the [FormsAppCompat](https://github.com/nativecode-dev/oss-xamarin/blob/master/src/NativeCode.Mobile.AppCompat.Renderers/FormsAppCompat.cs) type.

However, it sounds like you have a renderer that is inflating it's own Android layout resource. In that case, the package renderers shouldn't touch it because it only maps to Xamarin.Forms controls which shouldn't exist in your layout.

What's the exact problem you're running into?

**Comment by chrisriesgo** [comment]
Somewhere in code, you're wrapping the android content view in a
coordinator layout (and maybe another level of layout) which is causing a
view which previously laid out correctly to not work the same. I'll see if
I can repro it for you, but if you have thoughts before I can, I'd like to
hear your ideas.

**Comment by mikepham** [comment]
Ahhh, yeah there's a CoordinatorLayout in the AppCompatFormsActivity that's created before the Xamarin.Forms LinearLayout is added. I'll add a switch to remove it.

**Comment by mikepham** [comment]
Fixed in merge [cb5bef7231dea82ffdccd0dc89ba4510451c1d11](https://github.com/nativecode-dev/oss-xamarin/commit/cb5bef7231dea82ffdccd0dc89ba4510451c1d11). Building Nuget packages now, should be 1.0.0.71.

The CoordinatorLayout is now disabled by default (it's not added to the content) and has to be manually enabled, so that should fix your layout issues with just an update.

**Comment by mikepham** [comment]
Closing this issue. Hopefully, removing the default CoordinatorLayout has fixed your issue.

**Comment by chrisriesgo** [comment]
Sorry, Mike. Was at a conference all day yesterday. It did fix the issue.
